---
output: pdf_document
---

American society is plagued by the stereotype that Black people engage in criminal activity and violence [@Quillian2001; @Welch2007], which heightens perceptions of threat from these individuals [@Cottrell2005]. For instance, Black men are perceived as substantially more threatening when they are taller than average compared to White men [@Hester2018]. Other research shows that Black men are perceived as physically larger (i.e., taller and heavier) and more capable of physical harm compared to White men [@Wilson2017]. Overall, this line of research suggests that Black men are more likely to be the targets of stereotypes about their capacity to threaten others' physical safety, even when they do not pose any threat.

These perceptions contribute to institutional racism, where these individuals face systematic barriers across several domains. For instance, Black people may face differential treatment within the criminal justice system, where they are more likely to be wrongly convicted and punished more harshly for crimes. In support of this argument, eyewitnesses are more likely to select a Black man with prototypically Black facial features (e.g., wide nose, thick lips) as the offender when presented in a line-up of suspects, even when the individual did not commit the crime [@Knuycky2014]. Also, men that look prototypically Black are more likely to be sentenced to death when they have been convicted of murdering a White victim compared to a Black victim [@Eberhardt2006]. Finally, individuals are more likely to shoot unarmed Black men in first-person shooter tasks [@Correll2007]. Another domain that may be affected by these stereotypes is the marketplace, where it has been demonstrated across numerous studies that there is employment discrimination against non-Whites and that Black individuals have poorer market outcomes relative to their White counterparts [@Ayres2015; @Doleac2013; @Riach2002], which may contribute to the enduring disparity in socioeconomic status (SES) between Black and White individuals [@Hayward2000]. For example, @Ayres2015 manipulated the skin color of the hands holding cards during a baseball card auction on eBay and found that Black sellers received fewer offers than Whites. On the occasions that Black sellers received offers, these offers were substantially lower than offers to White sellers. Researchers suggest that a lack of trust towards Black sellers contributes to these pattern of results [@Doleac2013], which may be due to the prominent stereotype about their threateningness.

The persistence and pervasiveness of these targeted stereotypes about threat based upon group membership may be explained by human evolutionary history. Specifically, lethal conflict plagued many inter-group encounters [@Bowles2009; @Neuberg2008], increasing the salience of group membership and strengthening the association between group membership and perceived threat. In the racially heterogeneous environment of America today, where cues that may indicate group membership are especially conspicuous, people assess threat potential from others using these superficial cues (e.g., skin color), even when they do not accurately reflect an individuals' threat potential [@Neuberg2016].

People may also attend to other characteristics outside of group membership, like facial and vocal characteristics, when assessing threat potential. For instance, research suggests that humans rapidly and automatically categorize faces along two dimensions: perceived valence and dominance [@Todorov2008]. The valence dimension reflects ratings of trustworthiness, while the dominance dimension maps onto ratings of dominance. Feelings of threat may be magnified when an individuals' facial features have high ratings on the dominance dimension and low ratings on the valence dimension [@Oosterhof2008], largely because people perceive these individuals as willing to (as induced by the valence dimension) and capable of (as induced by the dominance dimension) threatening others. With regards to vocal characteristics, there is extensive empirical evidence that lower-pitched voices are associated with greater threat potential, which is reflected by arm strength and testosterone levels [@Hodges-Simeon2014; @Puts2012]. Humans have androgen receptors in their vocal folds [@Voelter2008], which are sensitive to peripubertal exposure to testosterone. With higher levels of testosterone applied to the vocal fold receptors, the vocal chords will thicken and vibrate more slowly [@Harries1998], which in turn produces a lower pitch. In this way, voice pitch serves as an honest signal of threat potential, which makes people especially likely to use voice pitch as an indicator of threat potential [@Hodges-Simeon2015; @Hodges-Simeon2014]. Along these lines, men who have a lower-pitched voice are more likely to be perceived as dominant and untrustworthy [@OConnor2017; @Puts2010; @Puts2006].

Since we are more likely to perceive certain out-group members as threatening based upon different stereotypes that permeate throughout our culture, individuals within these groups that have disarming mechanisms (i.e., personal characteristics that reduce perceptions of threat) are more likely to be successful. This has been supported by previous research, where psychologists have shown that there are more baby-faced Black male CEO's than baby-faced White male CEO's and that Black male CEO's with a baby-faced appearance are more likely to be successful [@Livingston2009]. The researchers suggest that these individuals were perceived as more trustworthy in a social context dominated by out-group members (e.g., corporate America) and may be more successful than other individuals within their racial group because their facial features serve as a cue to their low threat potential, which improves their interpersonal interactions in that specific social context. In support of this argument, researchers show that other personal characteristics, like sexual orientation, can serve as a disarming mechanism for Black men in leadership positions, where gay Black men are rated as better leaders compared to single-minority men (i.e., gay men or Black men) [@Wilson2017]. The researchers suggest that these effects can be explained by a stereotype that gay men are less masculine, which reduces perceived threat.

Perceptions of leadership ability are likely to be affected by stereotypes and personal characteristics because people do not want leaders that they perceive as a threat to their group, as suggested by the research about leadership in baby-faced and gay Black men. Additionally, the prototypical leader is a White man, where White men are rated as more effective leaders compared to individuals within other racial groups [@Rosette2008], so Black men must be perceived as especially trustworthy and competent to overcome these biases. Based upon these premises, perceptions of dominance and trustworthiness from the voice in combination with perceived threat potential based upon stereotypes about Black people will likely affect ratings of their leadership ability. Specifically, Black men with vocal characteristics that elicit trust and decrease perceptions of dominance may be attributed leadership traits to a greater extent than Black men with voices that are perceived as threatening. Although previous research suggests that voice pitch has an effect upon leadership selection, where male CEOs with lower-pitched voices tend to be more successful [@Mayew2013], there is no research examining the interaction between race and voice pitch upon perceived leadership ability.

The current study makes an important contribution by examining the effects of stereotypes and vocal characteristics upon one's success in leadership positions and their perceived threateningness. We focus on vocal characteristics because the voice can be modulated volitionally [@Fraccaro2013; @Hughes2014; @Pisanski2016], and individuals are constantly provided auditory feedback during speech, which facilitates precision in encoding. This is in stark contrast to encoding of facial expressions, which cannot be monitored without outside assistance, so it is more difficult to exert as much control over encoding intended facial expressions effectively. Through vocal modulation, individuals can exert precise control over how others perceive them, which may facilitate their social goals [@Fraccaro2011]. In the case of Black men, they may modulate their voice to reduce perceptions of threat and increase perceived leadership ability in settings where they are the minority, like corporate America. If this is the case, it is imperative to determine whether vocal characteristics can serve as a disarming mechanism, which underlies the goals of the current experiment.

Through our experiment, we examined whether voice pitch differentially modulates perceptions of threat and leadership ability for Black and White men by creating recordings for participants, then randomly assigning them to four conditions with different voices and names, which served as our manipulation of voice pitch and group membership, respectively. We chose to exclude women from the sample of stimuli for this study because we anticipated that the interaction effect between race and voice pitch would be stronger amongst men. According to the out-group male target hypothesis [@Navarrete2010], out-group men are more likely to be perceived as threatening since men were more likely to engage in inter-group conflict throughout our evolutionary history. Empirical evidence shows that Black men are more likely to be perceived as a threat to physical safety compared to Black women [@Sidanius2000], which can amplify fearful responding towards Black men when an individual feels vulnerable to threat [@Maner2005].

We hypothesized that participants would rate Black men with high-pitched voices lower on traits associated with threat and higher on traits associated with leadership ability compared to Black men with low-pitched voices. On the other hand, White men with a low-pitched voice will be rated higher on traits associated with leadership ability compared to White men with a high-pitched voice, as suggested by previous research [@Klofstad2012]. For our secondary hypotheses, we anticipated that perceived trustworthiness would be negatively related to perceived threat, while perceived dominance would be positively related to perceived threat.We also expected main effects of race and voice pitch upon perceived trustworthiness and perceived dominance, where Black men would be perceived as less trustworthy, while low-pitched voices would be rated as more dominant.