---
output: pdf_document
---
Overall, we found that voice pitch has a significant effect upon perceived threat and leadership, where lower-pitched voices were rated as more threatening and better leaders compared to their higher-pitched counterparts, replicating previous literature on this topic [@Hodges-Simeon2014; @Puts2012]. We also found an unexpected effect of race upon leadership, where Black men were rated significantly higher on perceived leadership compared to White men. This finding contradicted our expectations, since most other research on this topic suggests that White men are prototypical leaders and are much more likely to be rated higher on perceived leadership than other social groups [@Rosette2008]. Our original primary hypotheses were not supported, since we did not find the expected interaction effects of voice pitch and race on perceived threat or perceived leadership. With regards to our secondary hypotheses, we find support for our prediction that perceived trustworthiness and perceived dominance would be related to perceived threat in the expected directions. Specifically, perceived trustworthiness was negatively related to perceived threat and perceived dominance was positively related to perceived threat, even when we examined the relationship broken down by each condition, suggesting that it is a robust effect. This aligns with previous research examining the effect of the facial dominance and trustworthiness that combine to affect perceived threat [@Oosterhof2008], but no studies have examined this relationship based upon vocal characteristics and race before. Therefore, our study provides preliminary support for the notion that the observed effects of facial trustworthiness and dominance on threat can be generalized to other personal characteristics (i.e., the voice).

Regarding our other secondary hypotheses, we found a significant effect of race upon perceived trustworthiness, but in the opposite direction of our expectations, where Black men were rated as significantly more trustworthy compared to White men. Most of the literature in this domain suggests that Black men are perceived as less trustworthy [@Stanley2012; @Stanley2011], largely because of negative stereotypes that are applied to their social category. On the contrary, we did not find the expected effect of voice pitch upon perceived dominance, but instead found an unexpected effect of race, where White men were rated as significantly more dominant compared to Black men.

Since our findings regarding race and leadership ability were especially unexpected given previous research, we explored three potential explanations for the results. First, we showed that there is mixed evidence in favor of social demand effects upon our findings, where we did not find that participants rated the Black voices higher on leadership if they remembered the Black names better (i.e., performed better on the manipulation check), nor did they rate Black men higher for specific leadership positions (i.e., as a boss). These are assumptions we would expect to hold if participants were engaging in socially desirable responding. On the other hand, they rated Black men higher on perceived trustworthiness and lower on perceived dominance, which aligns with what we would expect if they were trying to avoid appearing biased against Black men. Although these analyses provide some support for socially desirable responding, participants did not rate Black men lower on perceived threat, which is a prominent stereotype applied to this social category that participants may try to avoid confirming if they were in fact concerned about being labeled as biased.

We also explored the possibility that contrast effects could explain our findings, where the order of presentation of the voice and name stimuli (i.e., names presented before voices) may have affected participants' ratings. Specifically, the shifting stereotypes model [@Biernat1991] posits that individuals within a negatively stereotyped social category will be rated higher on subjective ratings for stereotype-relevant traits because they are judged relative to others within their respective social category and as a result, have a lower threshold to surpass. In the case of our study, the names may have activated expectations about the vocal characteristics that they would hear in the recording, and when the voices completely exceeded those low expectations, they were rated as subjectively 'superior' to their White counterparts who had a higher threshold to exceed. Based upon these premises, we would expect that there should be a similar contrast effect for Black men on the threat measure, but there is no main effect of race. Additionally, voices that are rated higher on leadership should show a greater discrepancy between Black and White ratings, which we found across most voices, except for the voice that was rated highest on leadership. In that case, the voice was rated higher when it was assigned a White name compared to a Black name. It is possible that this voice deviated from the general pattern either because the pattern would not exist if we had sampled from a larger group of voices or because the voice was unique in its characteristics.

The third potential explanation that we explored was that the stereotypes that Black men are aggressive and dominant may have conferred higher ratings for the recorded individuals on perceived leadership, but only in the absence of threat. When individuals have personal characteristics that are perceived as dominant and aggressive, they are more likely to be selected as leaders, which is based upon evolutionary preferences that may no longer reflect leadership ability [@Klofstad2018; @VanVugt2008]. In this case, it is possible that stereotypes about race with regards to dominance and aggressiveness affected the leadership ratings. However, our assumptions for this explanation, where Black men would be rated higher on perceived dominance and participants would prefer a Black man holding a leadership position (i.e., boss), did not hold. Overall, our exploratory analyses suggest that there is a possibility that the main effect of race upon leadership may be attributed to contrast effects or social demand effects, but we would need to conduct further research to determine the underlying mechanisms for these results.

In future research, we intend to address several limitations in our methodology that may have affected our results. Specifically, we only used White male voices, most of whom were graduate students at the University of Pennsylvania, which allowed us to have a relatively homogeneous sample of stimuli. Although race cannot be detected from the voice, SES and education levels are reflected by vocal characteristics, so it is entirely possible that participants were expecting the stereotypical Black names (which tend to be associated with low SES) to have African American vernacular [@Labov2010]. However, the voices we used as stimuli were from individuals that were attaining a much higher standard of education (PhD students) compared to the average individual, which may be obvious in their speech patterns. Additionally, the threat item was not situated in any context (i.e., participants were not provided any background as to why the voices should be perceived as threatening), and it is possible that the ratings reflected different forms of perceived threat (i.e., physical threat, threat to resources, etc.). We observed the expected effect of voice pitch upon threat, which may reflect an innate understanding of how sounds can convey threat potential, which is observed even in infancy (e.g., larger objects produce a lower pitch) [@Vestergaard2009]. On the other hand, race is not an evolutionarily-relevant coalitional cue, but instead is constructed as a cue of coalitional alliances through ecological conditions [@Kurzban2001], so it is unlikely that the manipulation of race elicited the perceptions of threat to the same degree as the voice manipulations. Since the study was conducted online and approximately half (49.5%) of the participants indicated that they listened to the recordings through speakers, it is also possible that there may have been differences in the listening environment that prevented participants from picking up on the differences in our voice pitch manipulations. Finally, we did not ask participants whether they thought the study was real, which may have provided more information about our observed results, since it is entirely possible that participants answered the suspicion check to align with the cover story because they thought it might have been an attention check.

It is imperative that future research within this domain attempts to address some of these limitations and determine whether the results are generalizable and replicable. Future studies should recruit a more diverse sample for vocal stimuli, including women and people from different racial groups and education levels. It would be useful to ask participants to guess which race and education level each voice represents to determine whether these characteristics will moderate the relationship between the independent variables and perceived leadership. Other studies [@Hester2018] have included endorsement of stereotypes as a moderator for explaining higher ratings on stereotype-consistent items, which would be valuable in future extensions of this research. Finally, reversing the playback of the recordings may allow us to reduce the effects of speech content and vernacular upon participants' ratings.

It will also be important to disentangle the possible explanations for our unexpected effect of race upon perceived leadership. Specifically, researchers can overcome social demand effects by offering to pay participants to tell the truth. Future studies should use more objective measures of leadership, since contrast effects are more likely to appear when participants are rating stimuli on subjective measures (e.g., Likert-type items) because these ratings may vary across contexts, while objective measures are consistent, regardless of the target, the perceiver, or immediate environmental influences [@Biernat2003]. If future studies replicate the current study design but replace the leadership composite with objective measures and do not find a similar effect of race upon leadership, this will provide support for contrast effects upon our results.

Future extensions of this research will be fruitful in helping us fully understand the complex interplay of vocal characteristics and racial stereotypes in affecting person perception. As other research has demonstrated, Black men are more likely to be perceived as threatening [@Trawalter2008; @Wilson2017], which can be detrimental to their success in leadership positions when they are typically the minority in the corporate world. There is preliminary evidence in support of the concept that Black men that have disarming mechanisms may benefit from these personal characteristics in leadership positions [@Hester2018; @Livingston2009; @Wilson2017]. Although the current study did not find the expected interaction effects of voice pitch and race upon perceived threat and leadership, there is still room for improvement in the methodological design and we encourage future researchers to extend this line of work to explore possible explanations further.

This line of work is important in helping us disentangle the personal characteristics that have a major effect upon person perception. Since we are incapable of reading others' minds to assess their intentions, we usually must make judgments of their character based upon their personal characteristics, even if these traits may not always be linked to their trustworthiness and/or threat potential. In this way, stereotypes about their group (based upon their observable characteristics that cue group membership) and their personal characteristics that cue their ability to act upon any threatening intentions combine to predict trust towards that person.

The stereotype that Black people are a threat to physical safety and personal property has permeated largely because race and ecology are confounded in the United States, such that Black people are more likely to be impoverished, which is intricately linked with crime risk [@Williams1997; @Williams2016]. Along these lines, Black people are overrepresented in certain contexts that link them with threat to physical safety (e.g., prisons) [@Mauer2007; @Roberts2004]. Over time, Americans began to associate crime with any individuals categorized as Black [@Quillian2001]. These stereotypes are especially likely to be spread in the modern context, since there are a multitude of technologies available for communicating with numerous individuals regardless of interpersonal distance, which encourages the uniform and rapid spread of information across a culture. Also, popular press facilitates this stereotyping by reporting racialized crime stories that strengthen the association between race and physical threat [@Dixon2007; @Gilliam1996]. Through these mechanisms, stereotypes have become ingrained in the public conscious in America today, and continue to affect how Black people are treated daily, even after explicit prejudice has become less socially acceptable [@Murphy2013]. Since many of the stereotypes in America are rooted in protracted racial tensions throughout history, any intervention to reduce these stereotypes must be comprehensive, targeting the many factors that contribute to stereotypes about Black people. Specifically, it is possible that the voice may serve as a potent disarming mechanism that can reduce perceived threat in Black men, which we explored through the current study. This research provides an initial glimpse into how certain vocal characteristics can be affected by racial stereotypes, but future research needs to continue this line of work to enlighten us about the importance of nonverbal behavior in influencing perceptions of, and in turn, behavior towards minority individuals.
